export const CATEGORIES_ACTION_TYPES = {
    SET_CATEGORIES: 'category/SET_CATEGORIES_MAP',
    FETCH_CATEGORY_START: 'category/FETCH_CATEGORY_START',
    FETCH_CATEGORY_SUCCESS: 'category/FETCH_CATEGORY_SUCCESS',
    FETCH_CATEGORY_FAILED: 'category/FETCH_CATEGORY_FAILED',
}